### ISSUE TITLE
Directory Guide 관련 내용 공유드립니다.

### ISSUE THREAD

**Issue by kouz95** [cheese10yun/spring-guide#25]
안녕하세요. 먼저 정말 좋은 자료 공유해 주셔서 감사합니다! 😊
항상 블로그나 공유해 주신 자료들 통해 정말 많은 도움을 받고 있습니다.

Directory Guide 관련하여 여러 가지 시도도 해보고 공부해보면서 접한 방식이 있는데, Hexagonal Architecture를 적용하여 패키지를 나누는 방식이고, 실제로 적용해봤을 때도 의존의 방향을 도메인으로 집중시킬 수 있는 좋은 방법이라고 생각되더라구요!

> [[2019] DDD Lite@Spring](https://www.youtube.com/watch?v=TdyOH1xZpT8&t=2149s)
> 공부하면서 접하게된 영상이고, 약 35분에 헥사고날 아키텍처 소개, 약 38분 30초에 패키지 구조에 대해서 설명하십니다.

혹시라도 시간 괜찮으시다면 영상 확인해보시고, 내용이 괜찮다면 내용 추가해주시거나 PR 요청 보내드릴테니 검토해주시면 영광이겠습니다..!

다시 한번 좋은 내용 공유 감사드립니다!

**Comment by cheese10yun** [comment]
@kouz95 
PR 올려주시면 감사하겠습니다. 시간있을 때 저도 찾아 보도록할게요
