### ISSUE TITLE
오탈자 제보

### ISSUE THREAD

**Issue by sarguments** [cheese10yun/spring-guide#7]
https://cheese10yun.github.io/spring-guide-test-1/ 에서  '것보다 모' 부분이 글자가 누락된 것 같습니다.

모든 response에 대한 andExpect를 작성합니다. 간혹 .andExpect(content().string(containsString(""))) 이런 테스트를 진행하는데 특정 문자열이 들어 있는지 없는지 확인하는 것은 것보다 모
response에 하나라도 빠지거나 변경되면 API 변경이 이루어진 것이고 그 변경에 맞게 테스트 코드도 변경되어야 합니다.

**Comment by cheese10yun** [comment]
감사합니다. 오탈자 PR 남겨주셔서 close 하겠습니다.

제가 오타가 많은 편이긴 하네요... 정말 감사합니다.
